### ISSUE TITLE
Question about cost

### ISSUE THREAD

**Issue by 2i2i** [tellor-io/algorandTellorV2#53]
What is the cost of sending one data point?

Thinking about a web2 app supplying heartbeats via the oracle , to decide whether that would be economically feasible

Is it a single transaction a costs the min txn fee?

Edit: sry, did not know where else to ask, as discord link is expired

**Comment by tallywiesenberg** [comment]
Hi @2i2i sorry I missed you! There is no txn fee, but rather accounts that send transactions on Algorand need a minimum balance :)
